@base = http://localhost:3000/api

@source = posts

# Product

# @name get
GET {{base}}/{{source}}

###

# @name filter
GET {{base}}/{{source}}?index=0

###

# @name create
POST {{base}}/{{source}}
Content-Type: application/json

{
  "name": "test 2"
}

###

# @name update_put
PUT {{base}}/{{source}}/4
Content-Type: application/json

{
  "name": "test 3"
}

###

# @name update_patch
PUT {{base}}/{{source}}/4
Content-Type: application/json

{
  "name": "test 3"
}

###

# @name remove
DELETE  {{base}}/{{source}}/4
